// TODO: Generated by Gemini 3, try to find a better implementation if possible
export const autoCorrelate = (
  buffer: Float32Array,
  sampleRate: number,
): number | null => {
  // Perform a quick check to see if there is enough signal
  let size = buffer.length;
  let rms = 0;
  for (let i = 0; i < size; i++) {
    rms += buffer[i] * buffer[i];
  }
  rms = Math.sqrt(rms / size);
  if (rms < 0.01) return null; // Signal too weak

  // Trim the buffer to find the start and end of the signal
  let r1 = 0,
    r2 = size - 1;
  const threshold = 0.2;
  for (let i = 0; i < size / 2; i++)
    if (Math.abs(buffer[i]) < threshold) {
      r1 = i;
      break;
    }
  for (let i = 1; i < size / 2; i++)
    if (Math.abs(buffer[size - i]) < threshold) {
      r2 = size - i;
      break;
    }
  const trimmedBuffer = buffer.slice(r1, r2);
  size = trimmedBuffer.length;

  // Create an array of correlations
  const c = new Float32Array(size).fill(0);
  for (let i = 0; i < size; i++) {
    for (let j = 0; j < size - i; j++) {
      c[i] = c[i] + trimmedBuffer[j] * trimmedBuffer[j + i];
    }
  }

  // Find the first peak in the correlation
  let d = 0;
  while (c[d] > c[d + 1]) d++;
  let maxval = -1,
    maxpos = -1;
  for (let i = d; i < size; i++) {
    if (c[i] > maxval) {
      maxval = c[i];
      maxpos = i;
    }
  }

  // Frequency = Sample Rate / Period
  if (maxpos !== -1) {
    return sampleRate / maxpos;
  }
  return null;
};
