name: Build and Lint Project
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v3
        with:
          repository: "mklein994/sunrise-cli"
          path: sunrise-cli

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - uses: actions/checkout@v3
        with:
          path: playground-vue

      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            sunrise-cli/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('sunrise-cli/**/Cargo.lock') }}

      - run: wasm-pack build --target web sunrise-cli

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-node-${{ hashFiles('playground-vue/**/pnpm-lock.yaml') }}

      - name: Install
        working-directory: playground-vue
        run: |
          corepack enable pnpm
          pnpm install

      - name: Lint
        working-directory: playground-vue
        run: pnpm run lint:ci

      - name: Node Tests
        working-directory: playground-vue
        run: pnpm run test:node
        continue-on-error: true

      - name: Test with Coverage
        working-directory: playground-vue
        run: pnpm run coverage --isolate

      - name: Get Version String
        working-directory: playground-vue
        env:
          VITE_COMMIT_HASH: ${{ github.sha }}
        run: |
          VITE_VERSION_STRING="${GITHUB_REF_NAME} (${GITHUB_SHA:0:7} $(date -Is))"
          echo "VITE_VERSION_STRING=${VITE_VERSION_STRING}" >> "${GITHUB_ENV}"

      - name: Typecheck
        working-directory: playground-vue
        run: pnpm run typecheck

      - name: Build
        working-directory: playground-vue
        env:
          # This should correspond with 'sentry-cli releases propose-version'
          VITE_SENTRY_RELEASE: ${{ github.sha }}
          VITE_SENTRY_ENABLED: true
          VITE_COMMIT_HASH: ${{ github.sha }}
          VITE_SENTRY_DSN: https://931d497682d84de1ad9db23083a1a6c0@o1124115.ingest.sentry.io/6162360
          VITE_SENTRY_ENVIRONMENT: ${{ github.ref_name == 'main' && 'release' || 'development' }}
        run: pnpm run build:all

      - name: Setup Sentry
        working-directory: playground-vue
        run: |
          SHELL="${SHELL}" pnpm setup
          . "${HOME}/.bashrc"
          PNPM_HOME="${HOME}/.local/share/pnpm"
          echo "PNPM_HOME=${PNPM_HOME}" >> "${GITHUB_ENV}"
          echo "${PNPM_HOME}" >> "${GITHUB_PATH}"

      - name: Sentry Release
        working-directory: playground-vue
        env:
          SENTRY_ORG: matthew-klein
          SENTRY_PROJECT: matthew-klein
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          pnpm install --global @sentry/cli
          SENTRY_RELEASE="$(sentry-cli releases propose-version)"
          sentry-cli releases new $SENTRY_RELEASE
          sentry-cli releases set-commits --auto $SENTRY_RELEASE
          sentry-cli releases deploys $SENTRY_RELEASE new --env production
          sentry-cli releases files $SENTRY_RELEASE upload-sourcemaps --url-prefix '~/dist/assets' --validate ./dist/assets

      - name: Deploy to Cloudflare
        uses: cloudflare/pages-action@1 # https://github.com/marketplace/actions/cloudflare-pages-github-action
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: playground-vue
          directory: playground-vue/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
