name: Build and Lint Project
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "mklein994/sunrise-cli"
          path: sunrise-cli

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - uses: actions/checkout@v2
        with:
          path: playground-vue

      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            sunrise-cli/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('sunrise-cli/**/Cargo.lock') }}

      - run: wasm-pack build --target web sunrise-cli

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('playground-vue/**/pnpm-lock.yaml') }}

      - name: Install
        run: corepack pnpm install -C playground-vue

      - name: Lint
        run: corepack pnpm run -C playground-vue lint:ci

      - name: Build
        env:
          # This should correspond with 'sentry-cli releases propose-version'
          VITE_SENTRY_RELEASE: ${{ github.sha }}
        run: corepack pnpm run -C playground-vue build

      - name: Sentry Release
        env:
          SENTRY_ORG: matthew-klein
          SENTRY_PROJECT: matthew-klein
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          cd playground-vue
          corepack pnpm install --global @sentry/cli
          SENTRY_RELEASE=$(sentry-cli releases propose-version)
          sentry-cli releases new $SENTRY_RELEASE
          sentry-cli releases set-commits --auto $SENTRY_RELEASE
          sentry-cli releases deploys $SENTRY_RELEASE new --env production
