name: Build and Lint Project
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: playground-vue

      - uses: actions/checkout@v4
        with:
          repository: "mklein994/sunrise-cli"
          path: sunrise-cli

      - uses: actions/checkout@v4
        with:
          repository: "mklein994/date-diff"
          path: date-diff

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            sunrise-cli/target/
            date-diff/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('date-diff/**/Cargo.lock', 'sunrise-cli/**/Cargo.lock') }}

      - run: wasm-pack build sunrise-cli
      - run: wasm-pack build date-diff

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: "playground-vue/package.json"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "pnpm"
          cache-dependency-path: "playground-vue/pnpm-lock.yaml"

      - name: Install dependencies
        working-directory: playground-vue
        run: pnpm install

      - name: Cache ESLint
        uses: actions/cache@v4
        with:
          path: playground-vue/.eslintcache
          key: eslint-src-${{ hashFiles('playground-vue/package.json', 'playground-vue/eslint.config.js', 'playground-vue/pnpm-lock.yml') }}-${{ hashFiles('src/**') }}
          restore-keys: |
            eslint-src-${{ hashFiles('playground-vue/package.json', 'playground-vue/eslint.config.js', 'playground-vue/pnpm-lock.yml') }}-${{ hashFiles('src/**') }}
            eslint-src-${{ hashFiles('playground-vue/package.json', 'playground-vue/eslint.config.js', 'playground-vue/pnpm-lock.yml') }}-
            eslint-src-

      - name: Lint
        working-directory: playground-vue
        run: pnpm run lint:ci

      - name: Node Tests
        working-directory: playground-vue
        run: pnpm run test:node
        continue-on-error: true

      - name: Test with Coverage
        working-directory: playground-vue
        run: pnpm run coverage --poolOptions.threads.isolate true

      - name: Get Version String
        working-directory: playground-vue
        env:
          VITE_COMMIT_HASH: ${{ github.sha }}
        run: |
          VITE_VERSION_STRING="${GITHUB_REF_NAME} (${GITHUB_SHA:0:7} $(date -Is))"
          echo "VITE_VERSION_STRING=${VITE_VERSION_STRING}" >> "${GITHUB_ENV}"

      - name: Typecheck
        working-directory: playground-vue
        run: pnpm run typecheck

      - name: Build
        working-directory: playground-vue
        env:
          SENTRY_ORG: matthew-klein
          SENTRY_PROJECT: matthew-klein
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          # This should correspond with 'sentry-cli releases propose-version'
          VITE_SENTRY_RELEASE: ${{ github.sha }}
          VITE_SENTRY_ENABLED: true
          BUILDTIME_SENTRY_ENABLED: true
          VITE_COMMIT_HASH: ${{ github.sha }}
          VITE_SENTRY_DSN: https://931d497682d84de1ad9db23083a1a6c0@o1124115.ingest.sentry.io/6162360
          VITE_SENTRY_ENVIRONMENT: ${{ github.ref_name == 'main' && 'release' || 'development' }}
        run: pnpm run build:all

      - name: Deploy to Cloudflare
        working-directory: playground-vue
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: pnpm dlx wrangler pages deploy dist --project-name=playground-vue --branch="${{ github.ref_name }}"
